{
 "title": "AWS_DocumentDB",
 "description": "AWS documentDB dashboard from cloudwatch exporter",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Database Connection",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aws_docdb_database_connections_average",
     "legendFormat": "database_connections"
    }
   ]
  },
  {
   "title": "Database cursors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aws_docdb_database_cursors_average",
     "legendFormat": "database_cursors"
    }
   ]
  },
  {
   "title": "Cpu Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aws_docdb_cpuutilization_average",
     "legendFormat": "%"
    }
   ]
  },
  {
   "title": "Free Storage ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aws_docdb_free_local_storage_average",
     "legendFormat": "GB"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aws_docdb_freeable_memory_average",
     "legendFormat": "GB"
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "aws_docdb_read_latency_average", "legendFormat": "ms" }
   ]
  },
  {
   "title": "Write Latency",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aws_docdb_write_latency_average",
     "legendFormat": "ms"
    }
   ]
  },
  {
   "title": "Database Connections ",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_docdb_database_connections_average",
     "legendFormat": "database_connections"
    },
    {
     "expr": "aws_docdb_database_connections_max_average",
     "legendFormat": "database_connections_max"
    }
   ]
  },
  {
   "title": "Database Cursors ",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_docdb_database_cursors_average",
     "legendFormat": "database_cursors"
    },
    {
     "expr": "aws_docdb_database_cursors_max_average",
     "legendFormat": "database_cursors_max"
    }
   ]
  },
  {
   "title": "Cpu Utilization %",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aws_docdb_cpuutilization_average",
     "legendFormat": "cpu_utilization %"
    }
   ]
  },
  {
   "title": "Freeable Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "aws_docdb_freeable_memory_average",
     "legendFormat": "freeable_memory"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_docdb_index_buffer_cache_hit_ratio_average",
     "legendFormat": "index_buffer_cache_hit_ratio"
    },
    {
     "expr": "aws_docdb_buffer_cache_hit_ratio_average",
     "legendFormat": "buffer_cache_hit_ratio"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "aws_docdb_write_iops_average", "legendFormat": "DocumentDB Write_iops" },
    { "expr": "aws_docdb_read_iops_average", "legendFormat": "DocumentDB Read_iops" }
   ]
  },
  {
   "title": "Volume IOPS rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "aws_docdb_volume_read_iops_average",
     "legendFormat": "volume_read_iops"
    },
    {
     "expr": "aws_docdb_volume_write_iops_average",
     "legendFormat": "volume_write_iops"
    }
   ]
  },
  {
   "title": "Volume Bytes Used",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "aws_docdb_volume_bytes_used_average",
     "legendFormat": "volume_bytes_used"
    }
   ]
  },
  {
   "title": "Free Local Storage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "aws_docdb_free_local_storage_average",
     "legendFormat": "free_local_storage"
    }
   ]
  },
  {
   "title": "Disk Queue Depth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_docdb_disk_queue_depth_average",
     "legendFormat": "disk_queue_depth"
    }
   ]
  },
  {
   "title": "Throughtput",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "aws_docdb_read_throughput_average",
     "legendFormat": "read_throughput"
    },
    {
     "expr": "aws_docdb_write_throughput_average",
     "legendFormat": "write_throughput"
    },
    {
     "expr": "aws_docdb_network_throughput_average",
     "legendFormat": "network_throughput"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "aws_docdb_read_latency_average", "legendFormat": "read_latency" },
    {
     "expr": "aws_docdb_write_latency_average",
     "legendFormat": "write_latency"
    }
   ]
  },
  {
   "title": "Operations Documents",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_docdb_documents_deleted_average",
     "legendFormat": "documents_deleted"
    },
    {
     "expr": "aws_docdb_documents_inserted_average",
     "legendFormat": "documents_inserted"
    },
    {
     "expr": "aws_docdb_documents_returned_average",
     "legendFormat": "documents_returned"
    },
    {
     "expr": "aws_docdb_documents_updated_average",
     "legendFormat": "documents_updated"
    },
    {
     "expr": "aws_docdb_ttldeleted_documents_average",
     "legendFormat": "ttldeleted_documents"
    }
   ]
  },
  {
   "title": "Operation  Opcounters",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_docdb_opcounters_command_average",
     "legendFormat": "opcounters_command"
    },
    {
     "expr": "aws_docdb_opcounters_delete_average",
     "legendFormat": "opcounters_delete"
    },
    {
     "expr": "aws_docdb_opcounters_getmore_average",
     "legendFormat": "opcounters_getmore"
    },
    {
     "expr": "aws_docdb_opcounters_insert_average",
     "legendFormat": "opcounters_insert"
    },
    {
     "expr": "aws_docdb_opcounters_update_average",
     "legendFormat": "opcounters_update"
    }
   ]
  }
 ]
}